[window]
padding = {x = 2, y = 2}
decorations = "none"
opacity = 0.8
blur = false

[scrolling]
history = 10000
multiplier = 3

[cursor]
style = {shape = "Block", blinking = "Off"}
unfocused_hollow = true
blink_timeout = 0

[mouse]
hide_when_typing = true